-- V005：用户仓库数据范围
CREATE TABLE IF NOT EXISTS sjc_user_warehouse (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  sys_user_id BIGINT NOT NULL,
  warehouse_id BIGINT NOT NULL,
  is_delete TINYINT NOT NULL DEFAULT 0,
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_user_warehouse (sys_user_id, warehouse_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
